name: NFI opdracht CICD

on:
  workflow_dispatch:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - main


jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]

    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Linting with flake8
        continue-on-error: true
        run: flake8 .
      - name: Test with pytest
        run: pytest --html=pytest-results/report.html
      - name: Upload pytest test results
        uses: actions/upload-artifact@v4
        with:
          name: pytest-results
          path: pytest-results
        if: ${{ always() }}
      - name: Run python profiler
        run: pyinstrument -o profile.html -m pytest
      - name: Upload pyinstrument profile
        uses: actions/upload-artifact@v4
        with:
          name: pyinstrument-profile
          path: profile.html
        if: ${{ always() }}
